name: clip
channels:
  - pytorch
  - defaults
dependencies:
  - python #=3.10.4
  - pip
  #- cudatoolkit=11.3
  - pytorch=1.11.0
  #- torchvision=0.12.0
  #- numpy=1.19.2
  - pip:
    - tokenizers
    - ftfy
    - regex
    - tqdm
    - transformers==4.15.0
    - timm==0.4.12
    - clip
    #- gc
    - pandas
    - requests
    - torch
    - torchvision
    - Pillow
    - fairscale==0.4.4
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    #- -e https://github.com/pharmapsychotic/clip-interrogator.git
    #- -e git+https://github.com/salesforce/BLIP@main#egg=BLIP
    #- -e git+https://github.com/fragmede/BLIP@hack#egg=blip
    - -e ../BLIP/
    - -e .

variables:
  CARGO_NET_GIT_FETCH_WITH_CLI: 1
  PYTORCH_ENABLE_MPS_FALLBACK: 1
